# Generated by Django 3.1.4 on 2021-03-03 15:22

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(1, 'View post'), (2, 'Call number')])),
                ('date_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('content_connect', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_content', to='content.base_content')),
                ('user_connect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_profile', to='accounts.profile')),
            ],
        ),
    ]
