# Generated by Django 3.1.4 on 2021-02-20 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_base_content_notshow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_action',
            name='content_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.base_content'),
        ),
        migrations.AlterField(
            model_name='log_action',
            name='user_connect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
