# Generated by Django 3.1.4 on 2021-03-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_versionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'deactive'), (1, 'active')], default=0),
        ),
    ]
