# Generated by Django 3.1.4 on 2021-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0003_auto_20210306_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='urlmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
