# Generated by Django 3.1.4 on 2021-02-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210224_1309'),
        ('content', '0020_auto_20210224_1309'),
        ('Log', '0003_auto_20210224_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_action',
            name='content_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_content', to='content.base_content'),
        ),
        migrations.AlterField(
            model_name='log_action',
            name='user_connect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_profile', to='accounts.profile'),
        ),
    ]
