# Generated by Django 3.1.4 on 2021-03-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0004_urlmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='urlmodel',
        ),
    ]
