# Generated by Django 3.1.4 on 2021-03-17 08:12

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Log', '0005_delete_urlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'مفید'), (2, 'غیرمفید')], null=True)),
                ('date_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user_connect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile')),
            ],
        ),
    ]
