# Generated by Django 3.1.4 on 2021-03-17 08:42

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Log', '0006_feedbackmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'انتقادات و پیشنهادات', 'verbose_name_plural': 'انتقادات و پیشنهادات'},
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='date_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مفید'), (2, 'غیرمفید')], null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='user_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile', verbose_name='توسط کاربر'),
        ),
    ]
