# Generated by Django 3.1.4 on 2021-03-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0012_auto_20210318_1001'),
        ('Log', '0008_auto_20210317_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_payment', to='content.base_content')),
                ('userpayment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_payment', to='accounts.profile')),
            ],
        ),
    ]
