# Generated by Django 3.1.4 on 2021-03-03 15:22

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('key', models.CharField(blank=True, max_length=100, unique=True, verbose_name='کد ارسالی')),
                ('verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='1.jpg', upload_to=accounts.models.get_upload_path, verbose_name='تصویر کاربر')),
                ('city', models.CharField(max_length=30, verbose_name='شهر کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='اکانت کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربر',
            },
        ),
    ]
