# Generated by Django 3.1.4 on 2021-03-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=300)),
                ('userpushtoken', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pushtoken_profile', to='accounts.profile')),
            ],
        ),
    ]
