# Generated by Django 3.1.4 on 2021-03-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pushtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushtoken',
            old_name='Token',
            new_name='ptoken',
        ),
    ]
