# Generated by Django 3.1.4 on 2021-02-24 08:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210218_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='1.jpg', upload_to=accounts.models.get_upload_path),
        ),
    ]
