# Generated by Django 3.1.4 on 2021-03-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210325_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushToken',
        ),
    ]
