# Generated by Django 3.1.4 on 2021-02-24 09:39

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210224_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'پیامک', 'verbose_name_plural': 'پیامک'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=30, verbose_name='شهر کاربر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='1.jpg', upload_to=accounts.models.get_upload_path, verbose_name='تصویر کاربر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='اکانت کاربر'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='key',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='کد ارسالی'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='phonenumber',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تایید شده'),
        ),
    ]
