# Generated by Django 3.1.4 on 2021-04-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0050_base_content_banerstartshowtime'),
        ('accounts', '0005_auto_20210330_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.CharField(max_length=100, verbose_name='رسید بانکی')),
                ('status', models.SmallIntegerField(choices=[(1, 'پرداخت موفق'), (2, 'پرداخت ناموفق'), (3, 'کنسل شده')], null=True, verbose_name='وضعیت پرداخت')),
                ('totalpayment', models.CharField(max_length=20, verbose_name='پرداختی')),
                ('items', models.TextField()),
                ('contentpayment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.base_content', verbose_name='مربوط به آگهی')),
                ('userpayment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_profile', to='accounts.profile', verbose_name='توسط کاربر ')),
            ],
            options={
                'verbose_name': 'اطلاعات پرداخت',
                'verbose_name_plural': 'اطلاعات پرداخت',
            },
        ),
    ]
