# Generated by Django 3.1.4 on 2021-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210406_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='totalpayment',
            field=models.PositiveIntegerField(verbose_name='پرداختی'),
        ),
    ]
