# Generated by Django 3.1.4 on 2021-04-06 08:45

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210406_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='totalpayment',
            field=models.PositiveIntegerField(verbose_name='پرداختی'),
        ),
    ]
