# Generated by Django 3.1.4 on 2021-04-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_base_content_banerstartshowtime'),
        ('shop', '0005_auto_20210406_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contentpayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.base_content', verbose_name='مربوط به آگهی'),
        ),
    ]
