# Generated by Django 3.1.4 on 2021-04-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210406_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='items',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='contentpayment',
        ),
    ]
