# Generated by Django 3.1.4 on 2021-04-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210330_1143'),
        ('shop', '0007_auto_20210407_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='paymentModel',
        ),
    ]
