# Generated by Django 3.1.4 on 2021-03-03 15:22

import content.models
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('valid', models.SmallIntegerField(choices=[(1, 'تایید شده'), (2, 'تایید نشده'), (3, 'درحال بررسی')], default=3, verbose_name='تایید شدن')),
                ('phonenumber', models.CharField(max_length=12, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('NOTSHOW', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
        migrations.CreateModel(
            name='citymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='realstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='city_prob',
            fields=[
                ('base_content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.base_content')),
                ('district', models.CharField(max_length=20)),
            ],
            bases=('content.base_content',),
        ),
        migrations.CreateModel(
            name='employment',
            fields=[
                ('base_content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.base_content')),
                ('salary', models.IntegerField()),
            ],
            bases=('content.base_content',),
        ),
        migrations.CreateModel(
            name='tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.platform')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.base_content', verbose_name='آگهی')),
                ('user_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'لایک ها',
                'verbose_name_plural': 'لایک',
            },
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='modelAlbum', to='content.base_content')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=content.models.get_upload_path, verbose_name='تصویر')),
                ('mainpic', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesA', to='content.imagealbum', verbose_name='آلبوم')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس',
                'ordering': ['-mainpic'],
            },
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('category_title', models.CharField(max_length=50, unique=True, verbose_name='عنوان دسته بندی')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='category_images', verbose_name='تصویر دسته بندی')),
                ('slider', models.BooleanField(default=False, verbose_name='قابلیت اسلایدر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='content.group', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name_plural': 'گروه',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('blogpost_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.base_content')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmark', to='content.base_content', verbose_name='آگهی')),
                ('user_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bookmarks', to='accounts.profile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'علاقه مندی ها',
                'verbose_name_plural': 'علاقه مندی',
            },
        ),
        migrations.AddField(
            model_name='base_content',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_city', to='content.citymodel', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='base_content',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.group', verbose_name='دسته بندی'),
        ),
    ]
