# Generated by Django 3.1.4 on 2020-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
