# Generated by Django 3.1.4 on 2021-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
