# Generated by Django 3.1.4 on 2021-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210209_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mainpic',
            field=models.BooleanField(default=False),
        ),
    ]
