# Generated by Django 3.1.4 on 2021-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210304_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_content',
            name='NOTSHOW',
        ),
        migrations.AlterField(
            model_name='base_content',
            name='valid',
            field=models.SmallIntegerField(choices=[(1, 'تایید شده'), (2, 'تایید نشده'), (3, 'درحال بررسی'), (4, 'حذف شده')], default=3, verbose_name='تایید شدن'),
        ),
    ]
