# Generated by Django 3.1.4 on 2021-02-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0002_auto_20210213_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content_connect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.base_content'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
