# Generated by Django 3.1.4 on 2021-03-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210307_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='valid',
            field=models.SmallIntegerField(choices=[(1, 'تایید شده'), (2, 'تایید نشده'), (3, 'درحال بررسی'), (4, 'حذف شده')], default=3, verbose_name='وضعیت'),
        ),
    ]
