# Generated by Django 3.1.4 on 2021-02-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210203_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_group',
            fields=[
                ('sub_categoryname', models.CharField(max_length=50, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_group', to='content.group')),
            ],
        ),
    ]
