# Generated by Django 3.1.4 on 2021-03-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0005_delete_urlmodel'),
        ('content', '0004_auto_20210307_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_prob',
            name='base_content_ptr',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='base_content_ptr',
        ),
        migrations.DeleteModel(
            name='news',
        ),
        migrations.DeleteModel(
            name='realstate',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='platform',
        ),
        migrations.DeleteModel(
            name='city_prob',
        ),
        migrations.DeleteModel(
            name='employment',
        ),
        migrations.DeleteModel(
            name='platform',
        ),
        migrations.DeleteModel(
            name='tariff',
        ),
    ]
