# Generated by Django 3.1.4 on 2021-02-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210213_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_content',
            name='phonenumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
