# Generated by Django 3.1.4 on 2021-02-16 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_base_content_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='address',
        ),
        migrations.AddField(
            model_name='base_content',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='album',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelAlbum', to='content.base_content'),
        ),
    ]
