# Generated by Django 3.1.4 on 2021-03-09 11:54

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210308_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_content',
            name='expiretime',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
    ]
