# Generated by Django 3.1.4 on 2021-02-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0006_auto_20210216_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmark', to='content.base_content')),
                ('user_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.profile')),
            ],
        ),
    ]
