# Generated by Django 3.1.4 on 2021-03-09 13:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_base_content_expiretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='expiretime',
            field=django_jalali.db.models.jDateTimeField(blank=True),
        ),
    ]
