# Generated by Django 3.1.4 on 2021-02-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-mainpic']},
        ),
        migrations.AlterField(
            model_name='base_content',
            name='valid',
            field=models.BooleanField(default=None),
        ),
    ]
