# Generated by Django 3.1.4 on 2021-03-09 13:17

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210309_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='expiretime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
