# Generated by Django 3.1.4 on 2021-03-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210309_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='platformModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='base_content',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_city', to='content.citymodel', verbose_name='شهر'),
        ),
        migrations.CreateModel(
            name='tariffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('prize', models.PositiveIntegerField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_platform', to='content.platformmodel')),
            ],
        ),
        migrations.AddField(
            model_name='base_content',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.tariffmodel', verbose_name='تعرفه'),
        ),
    ]
