# Generated by Django 3.1.4 on 2021-02-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210220_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='valid',
            field=models.BooleanField(blank=True, choices=[(True, 'تایید'), (False, 'تایید نشد')], null=True),
        ),
    ]
