# Generated by Django 3.1.4 on 2021-03-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210317_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffmodel',
            name='platform',
        ),
        migrations.DeleteModel(
            name='platformModel',
        ),
    ]
