# Generated by Django 3.1.4 on 2021-02-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210220_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_content',
            name='NOTSHOW',
            field=models.BooleanField(default=False),
        ),
    ]
