# Generated by Django 3.1.4 on 2021-02-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_base_content_notshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='base_content',
            name='city',
        ),
        migrations.AddField(
            model_name='base_content',
            name='city_connect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_city', to='content.city'),
        ),
    ]
