# Generated by Django 3.1.4 on 2021-03-18 06:31

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20210318_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='expiretime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان انقضا'),
        ),
    ]
