# Generated by Django 3.1.4 on 2021-03-24 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210318_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffmodel',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
