# Generated by Django 3.1.4 on 2021-02-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210221_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='city_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_city', to='content.city'),
            preserve_default=False,
        ),
    ]
