# Generated by Django 3.1.4 on 2021-02-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20210221_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_content',
            old_name='city_connect',
            new_name='city',
        ),
    ]
