# Generated by Django 3.1.4 on 2021-03-24 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_tariffmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmodel',
            name='time',
            field=models.TimeField(choices=[(datetime.time(7, 0), '7:00 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(6, 0), '6:00 pm'), (datetime.time(7, 0), '7:00 pm'), (datetime.time(8, 0), '8:00 pm'), (datetime.time(9, 0), '9:00 pm')]),
        ),
    ]
