# Generated by Django 3.1.4 on 2021-02-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210221_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='city',
            new_name='citymodel',
        ),
    ]
