# Generated by Django 3.1.4 on 2021-02-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20210221_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_content',
            old_name='city',
            new_name='city_connect',
        ),
    ]
