# Generated by Django 3.1.4 on 2021-02-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210221_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_content',
            old_name='city_connect',
            new_name='city',
        ),
    ]
