# Generated by Django 3.1.4 on 2021-02-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20210221_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_city', to='content.citymodel'),
        ),
    ]
