# Generated by Django 3.1.4 on 2021-03-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20210327_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmodel',
            name='time',
            field=models.DurationField(),
        ),
    ]
