# Generated by Django 3.1.4 on 2021-03-27 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20210327_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmodel',
            name='time',
            field=models.DurationField(default=datetime.timedelta(days=5)),
        ),
    ]
