# Generated by Django 3.1.4 on 2021-02-24 08:02

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210224_1132'),
        ('content', '0018_auto_20210221_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bookmarks', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to=content.models.get_upload_path),
        ),
    ]
