# Generated by Django 3.1.4 on 2021-02-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20210224_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='valid',
            field=models.BooleanField(blank=True, choices=[(1, 'تایید شده'), (2, 'تایید نشده'), (3, 'درحال بررسی')], null=True, verbose_name='تایید شدن'),
        ),
    ]
