# Generated by Django 3.1.4 on 2021-03-27 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20210327_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmodel',
            name='time',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
