# Generated by Django 3.1.4 on 2021-02-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20210224_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='valid',
            field=models.SmallIntegerField(choices=[(1, 'تایید شده'), (2, 'تایید نشده'), (3, 'درحال بررسی')], default=3, verbose_name='تایید شدن'),
        ),
    ]
