# Generated by Django 3.1.4 on 2021-03-27 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20210327_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmodel',
            name='time',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='ساعت به صورت 00:00:00 وارد کنید'),
        ),
    ]
