# Generated by Django 3.1.4 on 2021-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20210224_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='title',
            field=models.CharField(max_length=60, verbose_name='عنوان'),
        ),
    ]
