# Generated by Django 3.1.4 on 2021-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20210224_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mainpic',
            field=models.BooleanField(default=False, unique=True, verbose_name='تصویر اصلی'),
        ),
    ]
