# Generated by Django 3.1.4 on 2021-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20210227_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mainpic',
            field=models.BooleanField(default=False, verbose_name='تصویر اصلی'),
        ),
    ]
