# Generated by Django 3.1.4 on 2021-03-27 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20210327_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmodel',
            name='time',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=3600), help_text='ساعت به صورت hours:minutes:seconds dayوارد کنیدمانند:12:23:00 6'),
        ),
    ]
