# Generated by Django 3.1.4 on 2021-03-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20210327_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffmodel',
            old_name='prize',
            new_name='price',
        ),
    ]
