# Generated by Django 3.1.4 on 2021-02-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20210227_2004'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='unique mainpic',
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
