# Generated by Django 3.1.4 on 2021-03-28 10:38

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20210327_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_content',
            name='tarifftime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان تعرفه'),
        ),
        migrations.AlterField(
            model_name='tariffmodel',
            name='time',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=3600), help_text='ساعت به صورت hours:minutes:seconds day وارد کنید  مانند: 6 12:23:00'),
        ),
    ]
