# Generated by Django 3.1.4 on 2021-02-28 06:36

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20210227_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
