# Generated by Django 3.1.4 on 2021-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20210328_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffmodel',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
