# Generated by Django 3.1.4 on 2021-03-01 06:44

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_image_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=content.models.get_upload_path, verbose_name='تصویر'),
        ),
    ]
