# Generated by Django 3.1.4 on 2021-03-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_tariffmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_tariff', to='content.tariffmodel', verbose_name='تعرفه'),
        ),
    ]
