# Generated by Django 3.1.4 on 2021-03-01 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20210301_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='album',
            field=models.OneToOneField(default=25, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='modelAlbum', to='content.base_content'),
            preserve_default=False,
        ),
    ]
