# Generated by Django 3.1.4 on 2021-03-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20210301_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='album',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelAlbum', to='content.base_content'),
        ),
    ]
