# Generated by Django 3.1.4 on 2021-03-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20210330_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='platformModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='اسم پلتفرم')),
            ],
            options={
                'verbose_name': 'پلتفرم',
                'verbose_name_plural': 'پلتفرم',
            },
        ),
        migrations.RemoveField(
            model_name='base_content',
            name='tariff',
        ),
        migrations.AddField(
            model_name='tariffmodel',
            name='content_connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_content', to='content.base_content', verbose_name='تعرفه'),
        ),
        migrations.AddField(
            model_name='tariffmodel',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_platform', to='content.platformmodel', verbose_name='مربوط به پلتفرم'),
        ),
    ]
