# Generated by Django 3.1.4 on 2021-03-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20210331_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='tariff',
            field=models.ManyToManyField(blank=True, related_name='content_tariff', to='content.tariffModel', verbose_name='تعرفه'),
        ),
    ]
