# Generated by Django 3.1.4 on 2021-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_auto_20210331_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='tariff',
            field=models.ManyToManyField(blank=True, help_text='برای انتخاب چند آگهی کلید ctrl را فشار دهید و سپس انتخاب کنید', related_name='content_tariff', to='content.tariffModel', verbose_name='تعرفه'),
        ),
    ]
