# Generated by Django 3.1.4 on 2021-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20210331_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_content',
            name='Special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='base_content',
            name='tariff',
            field=models.ManyToManyField(blank=True, related_name='content_tariff', to='content.tariffModel', verbose_name='تعرفه'),
        ),
    ]
