# Generated by Django 3.1.4 on 2021-03-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210331_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
