# Generated by Django 3.1.4 on 2021-03-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20210331_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='آیدی'),
        ),
    ]
