# Generated by Django 3.1.4 on 2021-03-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20210331_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmodel',
            name='platform',
            field=models.SmallIntegerField(choices=[(1, 'اپلیکیشن'), (2, 'تلگرام'), (3, 'اینستاگرام')], default=1, verbose_name='مربوط به پلتفرم'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='platformModel',
        ),
    ]
