# Generated by Django 3.1.4 on 2021-04-01 06:04

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20210331_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_content',
            name='tarifftime',
        ),
        migrations.AddField(
            model_name='base_content',
            name='startshowtime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان نمایش'),
        ),
    ]
