# Generated by Django 3.1.4 on 2021-04-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_auto_20210403_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffoptionsmodel',
            options={'verbose_name': 'تبصره', 'verbose_name_plural': 'تبصره'},
        ),
    ]
