# Generated by Django 3.1.4 on 2021-04-03 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_auto_20210403_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffoptionsmodel',
            name='descriptions',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='tariffoptionsmodel',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabsare', to='content.tariffmodel', verbose_name='مربوط به تعرفه'),
        ),
    ]
