# Generated by Django 3.1.4 on 2021-04-03 10:16

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20210403_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_content',
            name='validtime',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
    ]
