# Generated by Django 3.1.4 on 2021-04-03 10:36

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_auto_20210403_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='validtime',
            field=django_jalali.db.models.jDateTimeField(editable=False, null=True, verbose_name='تاريخ تاييد'),
        ),
    ]
