# Generated by Django 3.1.4 on 2021-04-06 05:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_auto_20210404_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_content',
            name='banerstartshowtime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان نمایش بنر '),
        ),
    ]
