# Generated by Django 3.1.4 on 2021-04-07 12:43

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_base_content_banerstartshowtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_content',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد '),
        ),
    ]
