# Generated by Django 3.1.4 on 2021-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_auto_20210407_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_content',
            name='tabsare',
            field=models.ManyToManyField(blank=True, related_name='notes', to='content.TariffOptionsModel', verbose_name='تبصره'),
        ),
    ]
