# Generated by Django 3.1.4 on 2021-04-08 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_base_content_tabsare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmodel',
            name='time',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=3600), help_text='ساعت به صورت hours:minutes:seconds day وارد کنید  مانند: 6 12:23:00', verbose_name='زمان تعرفه'),
        ),
    ]
