# Generated by Django 3.1.4 on 2021-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_auto_20210408_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'فعال'), (2, 'غیر فعال')], default=2, verbose_name='وضعیت'),
        ),
    ]
